// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-6kZ_Nk-XwrBGuFXkAAvUN_8p7THWFs',
    appId: '1:684230926752:web:796d21d239f22a080a04c5',
    messagingSenderId: '684230926752',
    projectId: 'wallpaper-app-80e6b',
    authDomain: 'wallpaper-app-80e6b.firebaseapp.com',
    storageBucket: 'wallpaper-app-80e6b.firebasestorage.app',
    measurementId: 'G-ZRCRC9QV9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWoexakUrOGe-eyCPIFhKQW5MaWAVsso',
    appId: '1:684230926752:android:121fd11b1525c76d0a04c5',
    messagingSenderId: '684230926752',
    projectId: 'wallpaper-app-80e6b',
    storageBucket: 'wallpaper-app-80e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBurX55khYYb-QpUF1bbMiSlYLxKdRFu28',
    appId: '1:684230926752:ios:94425c50421753030a04c5',
    messagingSenderId: '684230926752',
    projectId: 'wallpaper-app-80e6b',
    storageBucket: 'wallpaper-app-80e6b.firebasestorage.app',
    iosClientId: '684230926752-lheae85htbvpi9ovkst529qfnmq14q5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );
}
